### ISSUE TITLE
Roadmap BS3

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#195]
This issue is a simple copy of https://github.com/shinken-monitoring/mod-webui/blob/bs3/roadmap.md to keep tracking current developments.

## Layout:
- [ ] clean UI layout
- [x] design rules for hosts/services state
- [ ] boostrap themable layout + how-to

## All / Problems view:
- [x] simple and compact user interface
- [x] Github like filtering system

   - [x] filter on host/service name
   - [x] filter on host/service state
   - [x] filter acknowledged
   - [x] filter scheduled downtimes
   - [x] filter on business priority

- [x] bookmark filters
- [x] launch commands

## Host / service view:
- [ ] clean element view
- [x] launch commands
- [ ] custom views ... many discussions ... really interesting feature but not easily integrable ....
- [x] comments ... no modifications needed.
- [x] downtimes ... no modifications needed.
- [ ] acknowledgements ... what should be ? should it exists ?
- [ ] timeline ... what should be ?
- [x] impacts ... no modifications needed.
- [ ] history ... should be discussed ... how to get logs ... still need mongo DB ?
- [ ] any other tabs ... should be discussed!

## Common / User preferences
- [ ] improve preferences storage backend (Mongodb)
- [ ] configuration parameters in storage backend instead of cfg files
   
### Minemap:
- [ ] filterable
- [x] new design rules

### Hosts/services groups / tags:
- [ ] filterable
- [x] new design rules
- [ ] common plugin

### Worldmap:
- [ ] filterable
- [x] new design rules

## Features:
- [ ] tag an element as favorites (previous #9)
- [ ] nagvis integration (previous #8)

**Comment by maethor** [comment]
I can't check the boxes, but you can already mark some of them as done. The Github like filtering system is done, for instance.

You can also add an item to remake the pagination mecanism, and another to regroup hosts/services tags/groups in a common plugin that manages the four routes but use only one common template. I intent to work on these two tasks.

Thanks.

**Comment by mohierf** [comment]
Main idea is : 
- we have a list of ressources
- we display this list, after filtering, in : 
   - a table (problems view)
   - a minemap
   - a worldmap

We must consider groups/tags plugin as a kind of "filter build helper" ... why not include in this plugin a form to include/exclude ack/downtimes, choose resource type (host/service), choose resource state. It would not be that difficult ...

**Comment by maethor** [comment]
I'm not sure to understand what you are saying.

To me, the main goal of services/hosts groups/tags is to be used as a dashboard. Some user have told me they use host_groups at the office, displayed all day long on a TV as a dashboard of their infrastructure.

If you just want to display a group, you shouldn't get threw this view, you just type "hg:foo" in the filter engine.

With that said, yes, I think the filter engine should also be used in minemap, world map, impacts, etc. I'm working on this (the first step was last night, with the new search_hosts_and_services() function).

**Comment by mohierf** [comment]
You are right! Let us keep it simple ...

 When i wrote this *early morning* comment I did not yet had a look to the *nightly PR* ;-)

**Comment by maethor** [comment]
eheh :)

**Comment by maethor** [comment]
@mohierf It a lot of work, but I think you should convert all these checkboxes to issues, and regroup them in a 2.0 milestone.

**Comment by mohierf** [comment]
You are right ... not enough time yesterday evening :-) I wanted to track all the ideas first ...
