### ISSUE TITLE
Element view - relooking ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-webui#220]
Closes #216. This issue to keep tracking of the current progress ...

**Main features:**
- [x] element overview panel
  - [x] element notes 
  - [x] element actions

- [x] element groups

- [x] element tags, #199

- [x] host services overview

- [x] business rule alert

- [x] problem alert

**Element tabs:**

- [x] custom views

- [x] information

- [x] impacts

- [x] configuration

- [x] commands

- [x] comments

- [x] downtimes

- [x] graphs

- [x] dependency graph, #225

- [x] timeline, not available, see #53 

- [x] history

**Commands forms and actions:**

- [x] configuration tab:
  - [x] change a variable, but #224!

- [x] comments tab: 
  - [x] add
  - [x] delete
  - [x] delete all

- [x] downtime tab:
  - [x] add
  - [x] delete
  - [x] delete all

- [x] commands tab:
  - [x] add a comment 
  - [x] try to fix
  - [x] acknowledge
  - [x] recheck
  - [x] submit a check result
  - [x] send custom notification, not available at the moment
  - [x] change a custom variable, not in this tab but in configuration tab ...
  - [x] schedule a downtime

  - [x] toggle active checks, #226 
  - [x] toggle passive checks, #226
  - [x] toggle freshness check => removed because it does not exist for an element!
  - [x] toggle notifications
  - [x] toggle event handler, not available on an host/service basis, only for global system
  - [x] toggle flap detection

**Comment by maethor** [comment]
Can you push your work @mohierf? It's a dev branch after all.

**Comment by mohierf** [comment]
Yes, I will push in a few minutes ... you curious :-)

**Comment by maethor** [comment]
```
Traceback (most recent call last):
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui/module.py", line 416, in lock_version
    return f(**args)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/var/lib/shinken/modules/webui/lib/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui/plugins/eltdetail/views/eltdetail.tpl", line 357, in <module>
    %if params['tab_counters']=='yes':
KeyError: 'tab_counters'
```

Does'nt seem to work :)

**Comment by maethor** [comment]
For Guido's sake, use booleans in this dict :)

You can even use a simple list : 

```
params['tabs'] = ['info', 'additional', 'commands', …]
if 'info' in params['tabs']:
    pass
```

**Comment by mohierf** [comment]
You are right ... as I said, very first draft ! I am still cleaning ...

Do you want to clean this tab configuration part ? The idea was to define in the plugin config file, which tabs are to be displayed ... I don't know wether it is still interesting :/P We should auto-detect if tabs are to be present or not ... it would be better !

**Comment by maethor** [comment]
I agree, it's not useful.

Right now I'm working on the problem page. I don't want to conflit with your work in progress.

**Comment by maethor** [comment]
@mohierf should I fix the bug?

**Comment by mohierf** [comment]
I did ... but not yet commited.
